org: ahnafnafee
app: eas-discord-webhook
console: true
service: eas-discord-webhook

frameworkVersion: "3"

useDotenv: true

plugins:
    - serverless-dotenv-plugin

provider:
    name: aws
    architecture: arm64
    runtime: nodejs16.x
    region: us-east-1

package:
    patterns:
        - "!.git/**"
        - "!.gh-assets/**"
        - "!README.md"
        - "!assets/**"
        - "!.github/**"

functions:
    eas-build-webhook:
        handler: lambda.handler
        events:
            - http: ANY /
            - http: "ANY /{proxy+}"
