org: ahnafnafee
app: eas-discord-webhook
console: true
service: eas-discord-webhook

frameworkVersion: "3"

useDotenv: true

plugins:
- serverless-dotenv-plugin
- serverless-plugin-warmup

provider:
  name: aws
  architecture: arm64
  runtime: nodejs16.x
  region: us-east-1
  iamRoleStatements:
  - Effect: 'Allow'
    Action:
    - 'lambda:InvokeFunction'
    Resource:
    - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${self:service}-${opt:stage, self:provider.stage}-*

custom:
  warmup:
    default:
      enabled: true
      role: IamRoleLambdaExecution
      architecture: 'arm64'
    enabled: true
    events:
    - schedule: rate(5 minutes)
    prewarm: true
    concurrency: 1

package:
  patterns:
  - "!.git/**"
  - "!.gh-assets/**"
  - "!README.md"
  - "!assets/**"
  - "!.github/**"

functions:
  eas-build-webhook:
    handler: lambda.handler
    events:
    - http: ANY /
    - http: "ANY /{proxy+}"
