org: ahnafnafee
console: true
service: eas-build-notify

provider:
    name: aws
    architecture: arm64
    runtime: nodejs14.x
    region: us-east-1

package:
    patterns:
        - "!.git/**"
        - "!.gh-assets/**"
        - "!README.md"
        - "!assets/**"
functions:
    eas-build-webhook:
        handler: lambda.handler
        events:
            - http: ANY /
            - http: "ANY /{proxy+}"
        environment:
            EAS_SECRET_WEBHOOK_KEY: "REPLACE_ME"
            DISCORD_BOT_TOKEN: "REPLACE_ME"
            DISCORD_CHANNEL_ID: "REPLACE_ME"
            EXPO_DEFAULT_TEAM_NAME: "REPLACE_ME"
