service: eas-build-notify

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-1

package:
  exclude:
    - .git/**
    - .gh-assets/**
    - README.md
functions:
  eas-build-webhook:
    handler: lambda.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    environment:
      EAS_SECRET_WEBHOOK_KEY: "REPLACE_ME"
      SLACK_CLIENT_ID: "REPLACE_ME"
      SLACK_CLIENT_SECRET: "REPLACE_ME"
      SLACK_TOKEN: "REPLACE_ME"
      SLACK_SIGNING_SECRET: "REPLACE_ME"
      SLACK_CHANNEL: "REPLACE_ME"
